# Generated by Django 3.2.8 on 2021-11-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resturant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturant_name', models.CharField(max_length=128)),
                ('city_name', models.CharField(max_length=128)),
                ('resturant_adress', models.CharField(max_length=128)),
                ('descriptins', models.TextField()),
            ],
        ),
    ]
