# Generated by Django 3.2.8 on 2021-11-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodex_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resturant',
            old_name='resturant_adress',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='resturant',
            old_name='resturant_name',
            new_name='name',
        ),
    ]
